orbs:
  node: circleci/node@4.2.1

version: 2.1

jobs:
  build:
     docker:
       - image: docker
     steps:
       - checkout
       - run: echo "Building"
       - run: sleep 10
       - run: echo "Build Succeed"
  test:
    docker:
      - image: docker
    steps:
      - checkout
      - run: echo "Testing"
      - run: sleep 20
      - run: echo "Test Succeed"
  deploy:
    docker:
      - image: docker
    steps:
      - checkout
      - run: ehco "Deployed"
  

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - build
            - test
      - deploy:
          requires:
            - hold